apiVersion: v1
kind: Service
metadata:
  name: mail-egress
  namespace: mail-egress
  labels:
    app.kubernetes.io/name: mail-egress
spec:
  selector:
    app.kubernetes.io/name: mail-egress
  ports:
    - name: proxy
      port: 3128
      targetPort: proxy
